version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres-network
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    ports:
      - "9411:9411"
    networks:
      - postgres-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres-network

  config-server-ms:
    image: image-created-using-maven-wrapper
    container_name: config-server
    ports:
      - "8080:8080"
    depends_on:
      - service-registry-ms
    networks:
      - microservice-network
      - postgres-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  service-registry-ms:
    image: image-created-using-maven-wrapper
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin
    networks:
      - microservice-network
      - postgres-network

  company-ms:
    image: image-created-using-maven-wrapper
    container_name: company
    ports:
      - "8081:8081"
    depends_on:
      - service-registry-ms
      - config-server-ms
    networks:
      - microservice-network
      - postgres-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  job-ms:
    image: image-created-using-maven-wrapper
    container_name: job
    ports:
      - "8082:8082"
    depends_on:
      - service-registry-ms
      - config-server-ms
    networks:
      - microservice-network
      - postgres-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka

  review-ms:
    image: image-created-using-maven-wrapper
    container_name: review
    ports:
      - "8083:8083"
    depends_on:
      - service-registry-ms
      - config-server-ms
    networks:
      - microservice-network
      - postgres-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    image: image-created-using-maven-wrapper
    container_name: gateway
    ports:
      - "8084:8084"
    depends_on:
      - service-registry-ms
    networks:
      - microservice-network
      - postgres-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  postgres:
  pgadmin-data:

networks:
  postgres-network:
    driver: bridge
  microservice-network:
    driver: bridge
